### ISSUE TITLE
AttributeError: 'EnvRobosuite' object has no attribute 'base_env'

### ISSUE THREAD

**Issue by 19373254** [NVlabs/mimicgen#42]
Hi, when I run 
python mimicgen/scripts/prepare_src_dataset.py \
--dataset datasets/source/square.hdf5 \
--env_interface MG_Square \
--env_interface_type robosuite
I come cross the problem below:

Traceback (most recent call last):
  File "/home/yjj/shiyan/Sparse_Diffusion_policy/mimicgen_environments/mimicgen/scripts/prepare_src_dataset.py", line 256, in <module>
    prepare_src_dataset(
  File "/home/yjj/shiyan/Sparse_Diffusion_policy/mimicgen_environments/mimicgen/scripts/prepare_src_dataset.py", line 153, in prepare_src_dataset
    env=env.base_env,
AttributeError: 'EnvRobosuite' object has no attribute 'base_env'

I haven't solved the problem. Can you give me some help? Thanks very much!

**Comment by 19373254** [comment]
Oh, I think this is the reason. I am on the ab6c3dcb8506f7f06b43b41365e5b3288c858520 branch of robomimic.  It is suggested to install d0b37cf214bd24fb590d182edb6384333f67b661 branch in the installation instruction.         Thank you very much!
